### ISSUE TITLE
Cannot read property 'Context' of undefined

### ISSUE THREAD

**Issue by ffxsam** [joyent/node-sshpk#21]
I just started getting this error, which points to this block of code:

```js
function Local(i) {
	return (asn1.Ber.Context | asn1.Ber.Constructor | i);
}    
```

The strange thing is, this package hasn't been published/updated since September.

**Comment by ramk18** [comment]
@ffxsam any luck? Facing the same issue

**Comment by ramk18** [comment]
@ffxsam looks like a npm issue. Upgrade your npm.

**Comment by ffxsam** [comment]
It wasn't, but rather an issue with an unrelated build system. Closing.

**Comment by crizzy9** [comment]
Just go to sshpk in node_modules and do npm i
