### ISSUE TITLE
remove remaining usage of jodid25519

### ISSUE THREAD

**Issue by pravi** [joyent/node-sshpk#28]
jodid25519 is not maintained anymore and its author recommends switching to tweetnacl.

https://github.com/meganz/jodid25519/issues/10#issuecomment-298788879

**Comment by arekinath** [comment]
So, progress on removing jodid25519 began when we first brought in the tweetnacl dependency, back in 1.6.0 (we're currently at 1.13.0). It looks like the only thing left using jodid25519 is the support for X25519 DH, which is pretty easy to change over.

I've made https://cr.joyent.us/#/c/1911/ to change over this last piece
