### ISSUE TITLE
compatibility with Node 8 (DeprecationWarning)

### ISSUE THREAD

**Issue by k2s** [joyent/node-sshpk#31]
When running Node 8 with parameter `--pending-deprecation` I get message:
```
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
```
Deatils are here https://nodejs.org/en/blog/release/v8.0.0/#buffer-changes .

Solution is to replace `new Buffer()` with `Buffer.from()`. That would break compatibility with node before v5.10.0.

**Comment by arekinath** [comment]
Given that there are "no plans to remove the Buffer(num) constructor from Node.js" (according to the release notes), and that maintaining compatibility with earlier node versions is very important to us for this project (given we use it mostly on a mix of 4.x and 0.10.x in production), I think we will be leaving these calls as they are for now.
