### ISSUE TITLE
Introduced getpass since 1.8.1

### ISSUE THREAD

**Issue by emmansun** [joyent/node-sshpk#4]
Hi All,

It seems you introduced getpass module since 1.8.1, but getpass's license is MPL 2.0 but not MIT, any limitation to our usage?

**Comment by arekinath** [comment]
I've just changed the license on `getpass` to MIT as well, to make this simpler. There is no problem generally with combining MIT and MPL-2 works (MPL-2 is purely file-based), but the `getpass` code is so small, honestly, that it seems easier to just make it MIT.

Hope that helps!
