### ISSUE TITLE
x509 cert string type mangling breaks chains

### ISSUE THREAD

**Issue by arekinath** [joyent/node-sshpk#40]
According to the X509 RFC, cert chain validators are free to assume that if a DN attribute's string types differ, they are not a valid match. Currently, the x509 generation code in `identity.js` always generates `PrintableString` attribute values where the characters in the string can be contained in the ASCII set. This unfortunately means that if we, say, read in a certificate that has `UTF8String` attributes in its subject DN and copy that into a new certificate's issuer DN, some implementations (notably `libnss`) will not consider the resulting certificate's issuer DN and the other cert's subject DN to be a match, and will not follow the signing chain.

**Comment by roccomuso** [comment]
is this change gonna be merged?

**Comment by arekinath** [comment]
Yeah, this will be released as part of 1.13.2 today.
