### ISSUE TITLE
./key and ./privateKey circular dependency

### ISSUE THREAD

**Issue by rbalicki2** [joyent/node-sshpk#5]
Hello,

When this module is required in a Jest test, I get the following error on the following line in `private-key.js`, because Key is a placeholder:

`util.inherits(PrivateKey, Key);`

The error is `TypeError: The super constructor to inherits must have a prototype.`, due to the fact that `./key` cannot be used an entry point (i.e. sshpk only works if `./private-key` requires `.key`). Jest recurses through each dependency in order to attempt to auto-mock it, and at each step loses information about past `require` calls. So, when it calls `require('./key')`, `Key` is `{}` in `./private-key`, and `util.inherits` correctly complains.

It seems like this should be solved by refactoring the code to not have a circular dependency. Thoughts?

-R

**Comment by rbalicki2** [comment]
FWIW, adding this to our tests fixes the issue:

`jest.unmock('sshpk');`

**Comment by arekinath** [comment]
This circular dep works fine in the actual code -- setting your prototype to something that hasn't been completely filled out yet but is filled in immediately after is perfectly valid Javascript. I know it's annoying that it breaks your testing tools, but unfortunately that refactor is also quite annoying... is the `.unmock()` workaround satisfactory for you?

**Comment by rbalicki2** [comment]
Yes, completely

**Comment by acdcjunior** [comment]
Hey, there. That error is comming up when we use Rollup to bundle sshpk (among other things).

I have changed that line to the following:

    setTimeout(() => { util.inherits(PrivateKey, key); });

It seems to work, but we can't tell if there are unexpected effects. Can you guys tell if this is OK or not?
